language: python
sudo: false
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.3 MODELDICT=1.2.0
  - DJANGO=1.5 MODELDICT=1.2.0
  - DJANGO=1.4.3 MODELDICT=1.4.1
  - DJANGO=1.5 MODELDICT=1.4.1
  - DJANGO=1.6 MODELDICT=1.4.1
  - DJANGO=1.7 MODELDICT=1.4.1
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7 MODELDICT=1.4.1
install:
  - pip install Django==$DJANGO
  - pip install django-modeldict==$MODELDICT
  - pip install flake8
  - pip install -e .
script:
  - make test
